files:
  - source: '*/lang/box/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        ar-SA: ar-sa
        de: de
        es-ES: es-es
        fr: fr
        it: it
        ja: ja
        ko: ko-kr
        lv: lv
        nl: nl-nl
        pt-BR: pt-br
        ru: ru
        sv-SE: sv-se
        vi: vi-vn
        zh-CN: zh-cn
        zh-TW: zh-tw
  - source: '*/i18n/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        ar-SA: ar-sa
        de: de
        es-ES: es-es
        fr: fr
        it: it
        ja: ja
        ko: ko-kr
        lv: lv
        nl: nl-nl
        pt-BR: pt-br
        ru: ru
        sv-SE: sv-se
        vi: vi-vn
        zh-CN: zh-cn
        zh-TW: zh-tw
  - source: '*/i18n/*/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        ar-SA: ar-sa
        de: de
        es-ES: es-es
        fr: fr
        it: it
        ja: ja
        ko: ko-kr
        lv: lv
        nl: nl-nl
        pt-BR: pt-br
        ru: ru
        sv-SE: sv-se
        vi: vi-vn
        zh-CN: zh-cn
        zh-TW: zh-tw
  - source: '*/i18n/*/conf/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        ar-SA: ar-sa
        de: de
        es-ES: es-es
        fr: fr
        it: it
        ja: ja
        ko: ko-kr
        lv: lv
        nl: nl-nl
        pt-BR: pt-br
        ru: ru
        sv-SE: sv-se
        vi: vi-vn
        zh-CN: zh-cn
        zh-TW: zh-tw
